name: Publish MCP Server

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      # Verification steps
      - name: Check if NPM_TOKEN secret exists
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "❌ NPM_TOKEN secret is not set"
            exit 1
          else
            echo "✅ NPM_TOKEN secret exists"
          fi

      - name: Verify NPM authentication
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check package.json exists
        run: |
          if [ ! -f "package.json" ]; then
            echo "❌ package.json not found"
            exit 1
          else
            echo "✅ package.json found"
            cat package.json | grep -E '"name"|"version"'
          fi

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
